/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package n3_livraria2;

import fatec.com.br.persistencia.Banco;
import fatec.com.br.persistencia.LivroDAO;
import java.awt.Color;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class FormAvancado extends javax.swing.JFrame {
    Banco banco = new Banco("root","","3306", "localhost","livraria");
    /**
     * Creates new form FormAvancado
     */
    public FormAvancado() {
        initComponents();
        getContentPane().setBackground(Color.getHSBColor(0.650f,0.158f,0.750f));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRelatorio1 = new javax.swing.JButton();
        btRelatorio2 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        miLivro = new javax.swing.JMenuItem();
        miAutor = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAltLivro = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livraria -Administração-");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 600));
        setResizable(false);

        btRelatorio1.setText("Relatorio de Vendas 1");
        btRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorio1ActionPerformed(evt);
            }
        });

        btRelatorio2.setText("Relatorio de Vendas 2");

        btNovo.setText("Gerenciar Livros");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jMenu1.setText("Cadastros");

        jMenu2.setText("Novo");

        miLivro.setText("Livro");
        miLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLivroActionPerformed(evt);
            }
        });
        jMenu2.add(miLivro);

        miAutor.setText("Autor");
        miAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAutorActionPerformed(evt);
            }
        });
        jMenu2.add(miAutor);

        jMenuItem3.setText("Categoria");
        jMenu2.add(jMenuItem3);

        jMenu1.add(jMenu2);

        jMenu3.setText("Alterar");

        miAltLivro.setText("Livro");
        miAltLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltLivroActionPerformed(evt);
            }
        });
        jMenu3.add(miAltLivro);

        jMenuItem5.setText("Autor");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Categoria");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Usuario");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Relatorios");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem8.setText("Vendas");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Autores");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Lucros");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRelatorio1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btRelatorio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(828, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btNovo)
                .addGap(18, 18, 18)
                .addComponent(btRelatorio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRelatorio2)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1013, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        FormNovoLivro novoLivro = new FormNovoLivro();
        novoLivro.setVisible(true);
        
    }//GEN-LAST:event_btNovoActionPerformed

    private void miLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLivroActionPerformed
        // TODO add your handling code here:]
        FormNovoLivro novoLivro = new FormNovoLivro();
        novoLivro.setVisible(true);
    }//GEN-LAST:event_miLivroActionPerformed

    private void miAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAutorActionPerformed
        // TODO add your handling code here:
        FormNovoLivro novoLivro = new FormNovoLivro();
        novoLivro.setVisible(true);
        
        
    }//GEN-LAST:event_miAutorActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        LivroDAO livroDAO = new LivroDAO(banco);
        banco.abrir();
        maisVendidos(livroDAO.relatorioVenda());
        banco.fechar();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void miAltLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltLivroActionPerformed
        // TODO add your handling code here:
        FormNovoLivro novoLivro = new FormNovoLivro();
        novoLivro.setVisible(true);
    }//GEN-LAST:event_miAltLivroActionPerformed

    private void btRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorio1ActionPerformed
        // TODO add your handling code here:
        LivroDAO livroDAO = new LivroDAO(banco);
        banco.abrir();
        maisVendidos(livroDAO.relatorioVenda());
        banco.fechar();
    }//GEN-LAST:event_btRelatorio1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        LivroDAO livroDAO = new LivroDAO(banco);
        banco.abrir();
        maisVendidos(livroDAO.relatorioVenda());
        banco.fechar();
    }//GEN-LAST:event_jMenu4ActionPerformed
    public void maisVendidos(ResultSet rs){      
        try{    
            int qtdColunas = rs.getMetaData().getColumnCount();
            PrintWriter out = new PrintWriter("E:/relatorioVendas.html");
            out.println("<html><body> Relatorio de vendas<br><br><center><table border=1>");
            out.println("<th>Quantidade</th><th>Titulo</th><th>Lucro</th>");
            while(rs.next()){ 
                    out.println("<tr>");
                    try{
                        String[] dados = new String[qtdColunas];
                        for(int i= 1; i<=qtdColunas; i++){
                            out.print("<td>"+rs.getString(i)+"</td>");
                        }
                    }catch(Exception ef){
                        System.out.println("Erro ao montar linha!");
                    }
                    out.println("</tr>");
            }
            out.println("</table></center></body></html>");
            out.close();
            JOptionPane.showMessageDialog(rootPane,"Sucesso!");
        }catch(Exception ee){
           System.out.println("Erro ao montar tabela!--"+ee);
        }
        try{  
         Runtime.getRuntime().exec("cmd.exe /c start firefox.exe file:///E:/relatorioVendas.html");  
        }  
        catch(IOException iOException)  
        {  
           JOptionPane.showMessageDialog(null,iOException); 
           JOptionPane.showMessageDialog(null,"Tente abrir o arquivo manualmente");
        }  
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btRelatorio1;
    private javax.swing.JButton btRelatorio2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem miAltLivro;
    private javax.swing.JMenuItem miAutor;
    private javax.swing.JMenuItem miLivro;
    // End of variables declaration//GEN-END:variables
}
